### PR TITLE
Add homebrew install instruction

### PR DESCRIPTION
**Pull request by cander**
There are instructions about how to upgrade when using Homebrew, but not how to install. (very trivial)

### CODE REVIEW

**Comment by simonw** [comment]
I stopped recommending Homebrew deliberately a couple of months ago:
- https://github.com/simonw/llm/issues/315#issuecomment-1783697556

Reason is that the Homebrew build currently uses Python 3.12, which means that plugins that use PyTorch (such as `llm-sentence-transformers`) can't be installed using that Homebrew package.

This sucks. Hopefully PyTorch will release a Python 3.12 build soon, at which point it stops being a problem:
- https://github.com/pytorch/pytorch/issues/110436

**Comment by simonw** [comment]
Hmm... that said, it looks like we do have a workaround:
- https://github.com/simonw/llm/issues/315#issuecomment-1879741434

So I could go back to recommending Homebrew but clearly document that workaround for when people need it.

**Comment by simonw** [comment]
That workaround works - running it in CI over here now to prove it:
- https://github.com/simonw/llm-sentence-transformers/pull/13

**Comment by cander** [comment]
Mostly, I was hoping for consistency - either install and update Hombrew, or no mention of Homebrew. Personally, I'm OK either way.

**Comment by simonw** [comment]
I'm going to handle this in this issue instead:
- https://github.com/simonw/llm/issues/397

**Pull request closed without merging**
