### PR TITLE
WIP: templates

### PR DESCRIPTION
**Pull request by simonw**
Refs:
- #23

TODO:

- [x] Implement the `llm -t name-of-template` bit
- [ ] Implement additional named parameters with `llm -t name-of-template -p name value`
- [ ] Tests
- [x] Implement the structure for the YAML - prompt, system and model (specifying default model) as a starting point
- [x] If a YAML file is just a string, load it as `prompt: that-string`
- [x] Better display for `llm templates list`
- [x] Documentation
- [ ] Some example templates

### CODE REVIEW

**Comment by simonw** [comment]
Docs preview here: https://llm--30.org.readthedocs.build/en/30/templates.html

**Comment by simonw** [comment]
Well this is fun...

```
% llm templates show summary
prompt: 'Summarize this: $input'
system: You speak like an enthusiastic Victorian explorer ALL THE TIME, with lots
    of flourishes
```
And then:
```
curl -s 'https://simonwillison.net/2023/Jun/15/when-zeppelins-ruled-the-earth/' | strip-tags -m | llm -t summary -m 4
```
> Huzzah! Gather 'round, dear friends, for I shall regale thou with an enthralling tale of Mr. Simon Willison's Weblog! He hath unveiled a captivating presentation from a bygone era - a wondrous time when Zeppelins ruled the Earth! Thou shalt revel in the delight of this aural and visual melange, crafted through the ingenious combination of yon historical slides and an MP3 recording, dating back to the 28th of October in the year 2008. Thus, embark on a jaunt through recent chronicles, touching on topics as diverse as understanding GPT tokenizers, adventures with ChatGPT, and courtroom communique with a dash of artifice. Verily, let me assure you, my good sirs and madams, that thou shalt procure nothing short of sheer intellectual delight in the exploration of these venerable pages!

**Comment by sderev** [comment]
Templates are really useful, yes.

For now, I use scripts for this purpose, which reduce the amount of typing at its minimum via autocompletion, and make it even easier to call in vim with a shebang command (`:.!command arg`).

Some examples of what I use: a thesaurus and a dictionary. Very short template, but also very useful.

### Thesaurus

```bash
% thesaurus an old car
Synonyms: vintage car, classic car, antique car, retro car, dated car, ancient car

Antonyms: new car, modern car, contemporary car, state-of-the-art car, cutting-edge car, advanced car
```

Script: 

```bash
#! /usr/bin/bash

# Combine all arguments into a single string
input="$*"

# Call the `llm` command with the modified input
llm --system "You are a multilingual thesaurus. You give synonyms and antonyms for words in the language they are provided in." "$input" --stream
```

### Dictionary

```bash
% define nimbleness
Definition: the quality of moving quickly and lightly; agility

Example sentence: The gymnast's nimbleness allowed her to perform the complicated routine with ease.
```

Script:

```bash
#! /usr/bin/bash

# Combine all arguments into a single string
input="$*"

# Call the `llm` command with the modified input
llm --system "You are a multilingual dictionary. Define the given word and create an example sentence using it, ensuring that both are in the language the word is most commonly used. If the language isn't clear, use English." "$input" --stream
```

Following the same idea, I also use `translate word` with another script. I'm gonna create other short commands like that from my prompts repertoire. I'm all ears for other practical ideas. The summary piping `curl`, `strip-tag`, and `llm` is a very good one :).

**Comment by simonw** [comment]
Those examples are great, thanks for that! Would you be OK with me including those prompts as examples in the documentation?

**Comment by sderev** [comment]
Sure, go ahead! I appreciate being credited :)

Another one I use a lot is this one: `proofread`

```bash
% proofread "Who's book is this?"
This sentence should be written as "Whose book is this?" The contraction "who's" is a combination of "who" and "is" and does not fit in this sentence. "Whose" is the correct possessive form of "who," indicating that this book belongs to someone and asking for the owner's identity. The syntax and overall structure of the sentence are correct.
```

Script:

```bash
#! /usr/bin/bash

# Checks if any arguments were passed to the script
if [[ -n "$@" ]]; then
    # Combine all arguments into a single string
    input="$*"
else
    # Read input from stdin
    read input
fi  

# Call the `llm` command with the modified input
llm --system "You are an expert English writer and grammarian. Review the following English sentence for grammatical correctness, syntax, and overall structure, and provide feedback as necessary. The sentence is:" "$input" --stream
```

**Comment by simonw** [comment]
Here's how to detect the named variables in a `string.Template`:

```pycon
>>> from string import Template
>>> t = Template("$foo and $bar")
>>> t.pattern
re.compile('\n            \\$(?:\n              (?P<escaped>\\$)  |   # Escape sequence of two delimiters\n              (?P<named>(?a:[_a-z][_a-z0-9]*))       |   # delimiter and a Python identifier\n          , re.IGNORECASE|re.VERBOSE)
>>> list(t.pattern.finditer(t.template))
[<re.Match object; span=(0, 4), match='$foo'>, <re.Match object; span=(9, 13), match='$bar'>]
>>> matches = list(t.pattern.finditer(t.template))
>>> matches
[<re.Match object; span=(0, 4), match='$foo'>, <re.Match object; span=(9, 13), match='$bar'>]
>>> matches[0]
<re.Match object; span=(0, 4), match='$foo'>
>>> matches[0][1]
>>> matches[0][0]
'$foo'
>>> matches[1][0]
'$bar'
>>> matches[0].groups()
(None, 'foo', None, None)
>>> matches[1].groups()
(None, 'bar', None, None)
>>> matches[1].groupdict()
{'escaped': None, 'named': 'bar', 'braced': None, 'invalid': None}
```

**Comment by simonw** [comment]
Here's a problem: thanks to this code it isn't currently possible to pipe content to the tool AND specify extra params:

https://github.com/simonw/llm/blob/0fc51f46c156793b23def2beeb446c1402f72483/llm/cli.py#L71-L73

So this doesn't work:

    cat file.txt | llm -t summarize -p voice GlaDOS

**Comment by simonw** [comment]
I can use `sys.stdin.isatty()` to try and detect that.

**Comment by simonw** [comment]
Documentation: https://llm--30.org.readthedocs.build/en/30/templates.html

**Pull request merged**
